version: '3'
services:
        web:
                container_name: http-server
                build:
                        context: ./
                ports:
                        - "8888:8888"
                command: ["python3", "main.py", "--app=http_app:app", "--workers=3"]

