version: '3.5'
services:
        server:
                build:
                        dockerfile: Dockerfile-http
                        context: ./
                ports:
                        - "8888:8888"
                networks:
                        - server_net
                        - fs_net
                environment:
                        - FS_SCALE=${FS_SCALE}
                command: ["python3", "main.py", "--app=http_app:app", "--workers=3"]

        fs:
                build:
                        dockerfile: Dockerfile-fs
                        context: ./
                networks:
                        - fs_net
                command: ["python3", "fs.py"]

networks:
        server_net:
                driver: bridge
        fs_net:
                driver: bridge

