version: '3.5'
services:
        server:
                build:
                        dockerfile: http.dockerfile
                        context: ./
                ports:
                        - "8888:8888"
                networks:
                        - server_net
                        - fs_net
                environment:
                        - FS_SCALE=${FS_SCALE}
                command: ["python3", "server/main.py", "${WORKERS}", "${FS_URL}", "${CACHE_SIZE}"]

        fs:
                build:
                        dockerfile: fs.dockerfile
                        context: ./
                networks:
                        - fs_net
                command: ["python3", "fs/main.py", "${FS_WORKERS}", "${FS_CACHE_SIZE}"]

networks:
        server_net:
                driver: bridge
        fs_net:
                driver: bridge

